spring:
  application:
    name: readhub

  datasource:
    url: jdbc:postgresql://localhost:5432/readhub
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

    jpa:
      hibernate:
        ddl-auto: validate
      show-sql: true
      properties:
        hibernate:
          format_sql: true

    flyway:
      enabled: true
      locations: classpath:db/migration

readhub:
  security:
    secret: "D0D43DC203A565BB0D2B970FFD804F36"